### ISSUE TITLE
incompatible naming convention

### ISSUE THREAD

**Issue by dispyfree** [michnaadam33/yii2-rbac-console#1]
Hi,

When installing the most recent version using composer plus Yii2, I encounter the following error message:

> php yii Exception 'ReflectionException' with message 'Class michnaadam33\rbacConsole\RbacConsole does not exist' in /vendor/yiisoft/yii2/di/Container.php:424

Stack trace:

> Stack trace:
#0 wwwRoot/www/vendor/yiisoft/yii2/di/Container.php(424): ReflectionClass->__construct('michnaadam33\\rb...')
#1 wwwRoot/www/vendor/yiisoft/yii2/di/Container.php(364): yii\di\Container->getDependencies('michnaadam33\\rb...')
#2 wwwRoot/www/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('michnaadam33\\rb...', Array, Array)
#3 wwwRoot/www/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('michnaadam33\\rb...', Array, Array)
#4 wwwRoot/www/vendor/yiisoft/yii2/base/Module.php(578): yii\BaseYii::createObject(Array, Array)
#5 wwwRoot/www/vendor/yiisoft/yii2/console/controllers/HelpController.php(196): yii\base\Module->createController('')
#6 wwwRoot/www/vendor/yiisoft/yii2/console/controllers/HelpController.php(288): yii\console\controllers\HelpController->getCommandDescriptions()
#7 wwwRoot/www/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#8 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)
#9 wwwRoot/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 wwwRoot/www/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#11 wwwRoot/www/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('', Array)
#12 wwwRoot/www/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('', Array)
#13 wwwRoot/www/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('', Array)
#14 wwwRoot/www/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('', Array)
#15 wwwRoot/www/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#16 wwwRoot/www/yii(20): yii\base\Application->run()
#17 {main}
valentin@BornToWork:~/Desktop/education/computer_science/projects/php/PsyConcept/www$ 

This is my console.php:
`'rbac-console' => [
            'class' => 'michnaadam33\rbacConsole\Collection',
        ],`

renaming the class "RbacController" to "RbacConsole" as well as renaming the file resolves the issue.

I believe that there is an issue with the Yii2 naming convention; a custom name can surely be set but isn't set in the standard configuration.

Thank you in advance!

**Comment by michnaadam33** [comment]
Hello,

Thank you for your issue report. I fixed it here [https://github.com/michnaadam33/yii2-rbac-console/commit/afe1a7317b9ac56e35ef1bd1fa5b7eca8b0f17c7](https://github.com/michnaadam33/yii2-rbac-console/commit/afe1a7317b9ac56e35ef1bd1fa5b7eca8b0f17c7)

You can check it by using:
```
"michnaadam33/yii2-rbac-console": "dev-master"
```
